/*  FOR LOOPS IN JAVASCRIPT */

/* var i ;
for( i =0 ; i <= 10 ; i++){
    console.log("Ayush"+i);
} */


/* WHILE LOOPS */


/* let ip = 0;

let house = 100;

while(ip!= house){
    ip = ip+1;
    console.log("step taken"+ip);
}; */




/* DO WHILE LOOPS */


/* let ip = 50; */
/* let house = 50;
do{

    ip = ip+1;
    console.log("Step Taken"+ip);

}while(ip<house);  */





