// ARRAYS

const student = ["ayush","piyush","sam","priyanshu","james"];

const myArr = [1,"Ayush","😂"];

const num = [1,2,3,4,5,6,7,8];


/* 


student.reverse();

student.pop();
student.push("rishi");

console.log(student); */


/* HIGH ORDER ARRAY FUNCTION */

/* 

    function print(n){
    console.log(n);
}

    student.forEach(print);


} */
  // or
 
 // student.forEach((val)=> console.log(val));


/* function double(n){
    return n*2;

};

const newArr = num.map(double);

console.log(newArr);
 */



/* var ans = num.find((val)=> val === 4);

console.log(ans); */



/* function check(age){
    return age>5;
};

var ans = num.findIndex(check);

console.log(ans); */


/* function even(val){
   return val%2 == 0;
};

var ans = num.findIndex(even);

console.log(ans); */




/* var a = num.includes(4);
console.log(a); */

/* const newArr = num.filter( num=> num%2 == 0);

console.log(newArr);

 */

/* 
var newArr = num.slice(1,6);

console.log(newArr); */


/* var newArr = num.splice(2,4);

console.log(newArr);

console.log(num); */

/* var newArr = student .splice(0,3);

 console.log(newArr); */




 






















